apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  type: LoadBalancer
  loadBalancerIP: 35.203.129.116
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webserver
